/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "k8s.io/kubectl/pkg/kustomize/apis/packaging/v1alpha1"
	scheme "k8s.io/kubectl/pkg/kustomize/client/clientset/versioned/scheme"
)

// KitsGetter has a method to return a KitInterface.
// A group's client should implement this interface.
type KitsGetter interface {
	Kits(namespace string) KitInterface
}

// KitInterface has methods to work with Kit resources.
type KitInterface interface {
	Create(*v1alpha1.Kit) (*v1alpha1.Kit, error)
	Update(*v1alpha1.Kit) (*v1alpha1.Kit, error)
	UpdateStatus(*v1alpha1.Kit) (*v1alpha1.Kit, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Kit, error)
	List(opts v1.ListOptions) (*v1alpha1.KitList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Kit, err error)
	KitExpansion
}

// kits implements KitInterface
type kits struct {
	client rest.Interface
	ns     string
}

// newKits returns a Kits
func newKits(c *PackagingV1alpha1Client, namespace string) *kits {
	return &kits{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kit, and returns the corresponding kit object, and an error if there is any.
func (c *kits) Get(name string, options v1.GetOptions) (result *v1alpha1.Kit, err error) {
	result = &v1alpha1.Kit{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kits").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Kits that match those selectors.
func (c *kits) List(opts v1.ListOptions) (result *v1alpha1.KitList, err error) {
	result = &v1alpha1.KitList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kits").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kits.
func (c *kits) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kits").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a kit and creates it.  Returns the server's representation of the kit, and an error, if there is any.
func (c *kits) Create(kit *v1alpha1.Kit) (result *v1alpha1.Kit, err error) {
	result = &v1alpha1.Kit{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kits").
		Body(kit).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kit and updates it. Returns the server's representation of the kit, and an error, if there is any.
func (c *kits) Update(kit *v1alpha1.Kit) (result *v1alpha1.Kit, err error) {
	result = &v1alpha1.Kit{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kits").
		Name(kit.Name).
		Body(kit).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *kits) UpdateStatus(kit *v1alpha1.Kit) (result *v1alpha1.Kit, err error) {
	result = &v1alpha1.Kit{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kits").
		Name(kit.Name).
		SubResource("status").
		Body(kit).
		Do().
		Into(result)
	return
}

// Delete takes name of the kit and deletes it. Returns an error if one occurs.
func (c *kits) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kits").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kits) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kits").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kit.
func (c *kits) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Kit, err error) {
	result = &v1alpha1.Kit{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kits").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
