/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "k8s.io/kubectl/pkg/kustomize/apis/packaging/v1alpha1"
	scheme "k8s.io/kubectl/pkg/kustomize/client/clientset/versioned/scheme"
)

// PatchsetsGetter has a method to return a PatchsetInterface.
// A group's client should implement this interface.
type PatchsetsGetter interface {
	Patchsets(namespace string) PatchsetInterface
}

// PatchsetInterface has methods to work with Patchset resources.
type PatchsetInterface interface {
	Create(*v1alpha1.Patchset) (*v1alpha1.Patchset, error)
	Update(*v1alpha1.Patchset) (*v1alpha1.Patchset, error)
	UpdateStatus(*v1alpha1.Patchset) (*v1alpha1.Patchset, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Patchset, error)
	List(opts v1.ListOptions) (*v1alpha1.PatchsetList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Patchset, err error)
	PatchsetExpansion
}

// patchsets implements PatchsetInterface
type patchsets struct {
	client rest.Interface
	ns     string
}

// newPatchsets returns a Patchsets
func newPatchsets(c *PackagingV1alpha1Client, namespace string) *patchsets {
	return &patchsets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the patchset, and returns the corresponding patchset object, and an error if there is any.
func (c *patchsets) Get(name string, options v1.GetOptions) (result *v1alpha1.Patchset, err error) {
	result = &v1alpha1.Patchset{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("patchsets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Patchsets that match those selectors.
func (c *patchsets) List(opts v1.ListOptions) (result *v1alpha1.PatchsetList, err error) {
	result = &v1alpha1.PatchsetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("patchsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested patchsets.
func (c *patchsets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("patchsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a patchset and creates it.  Returns the server's representation of the patchset, and an error, if there is any.
func (c *patchsets) Create(patchset *v1alpha1.Patchset) (result *v1alpha1.Patchset, err error) {
	result = &v1alpha1.Patchset{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("patchsets").
		Body(patchset).
		Do().
		Into(result)
	return
}

// Update takes the representation of a patchset and updates it. Returns the server's representation of the patchset, and an error, if there is any.
func (c *patchsets) Update(patchset *v1alpha1.Patchset) (result *v1alpha1.Patchset, err error) {
	result = &v1alpha1.Patchset{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("patchsets").
		Name(patchset.Name).
		Body(patchset).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *patchsets) UpdateStatus(patchset *v1alpha1.Patchset) (result *v1alpha1.Patchset, err error) {
	result = &v1alpha1.Patchset{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("patchsets").
		Name(patchset.Name).
		SubResource("status").
		Body(patchset).
		Do().
		Into(result)
	return
}

// Delete takes name of the patchset and deletes it. Returns an error if one occurs.
func (c *patchsets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("patchsets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *patchsets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("patchsets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched patchset.
func (c *patchsets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Patchset, err error) {
	result = &v1alpha1.Patchset{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("patchsets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
