/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	packaging_v1alpha1 "k8s.io/kubectl/pkg/kustomize/apis/packaging/v1alpha1"
	versioned "k8s.io/kubectl/pkg/kustomize/client/clientset/versioned"
	internalinterfaces "k8s.io/kubectl/pkg/kustomize/client/informers/externalversions/internalinterfaces"
	v1alpha1 "k8s.io/kubectl/pkg/kustomize/client/listers/packaging/v1alpha1"
)

// PatchsetInformer provides access to a shared informer and lister for
// Patchsets.
type PatchsetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PatchsetLister
}

type patchsetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPatchsetInformer constructs a new informer for Patchset type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPatchsetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPatchsetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPatchsetInformer constructs a new informer for Patchset type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPatchsetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PackagingV1alpha1().Patchsets(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PackagingV1alpha1().Patchsets(namespace).Watch(options)
			},
		},
		&packaging_v1alpha1.Patchset{},
		resyncPeriod,
		indexers,
	)
}

func (f *patchsetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPatchsetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *patchsetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&packaging_v1alpha1.Patchset{}, f.defaultInformer)
}

func (f *patchsetInformer) Lister() v1alpha1.PatchsetLister {
	return v1alpha1.NewPatchsetLister(f.Informer().GetIndexer())
}
