/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/kubectl/pkg/kustomize/apis/packaging/v1alpha1"
)

// FakeKits implements KitInterface
type FakeKits struct {
	Fake *FakePackagingV1alpha1
	ns   string
}

var kitsResource = schema.GroupVersionResource{Group: "packaging.k8s.io", Version: "v1alpha1", Resource: "kits"}

var kitsKind = schema.GroupVersionKind{Group: "packaging.k8s.io", Version: "v1alpha1", Kind: "Kit"}

// Get takes name of the kit, and returns the corresponding kit object, and an error if there is any.
func (c *FakeKits) Get(name string, options v1.GetOptions) (result *v1alpha1.Kit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kitsResource, c.ns, name), &v1alpha1.Kit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kit), err
}

// List takes label and field selectors, and returns the list of Kits that match those selectors.
func (c *FakeKits) List(opts v1.ListOptions) (result *v1alpha1.KitList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kitsResource, kitsKind, c.ns, opts), &v1alpha1.KitList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KitList{}
	for _, item := range obj.(*v1alpha1.KitList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kits.
func (c *FakeKits) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kitsResource, c.ns, opts))

}

// Create takes the representation of a kit and creates it.  Returns the server's representation of the kit, and an error, if there is any.
func (c *FakeKits) Create(kit *v1alpha1.Kit) (result *v1alpha1.Kit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kitsResource, c.ns, kit), &v1alpha1.Kit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kit), err
}

// Update takes the representation of a kit and updates it. Returns the server's representation of the kit, and an error, if there is any.
func (c *FakeKits) Update(kit *v1alpha1.Kit) (result *v1alpha1.Kit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kitsResource, c.ns, kit), &v1alpha1.Kit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kit), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKits) UpdateStatus(kit *v1alpha1.Kit) (*v1alpha1.Kit, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kitsResource, "status", c.ns, kit), &v1alpha1.Kit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kit), err
}

// Delete takes name of the kit and deletes it. Returns an error if one occurs.
func (c *FakeKits) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kitsResource, c.ns, name), &v1alpha1.Kit{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKits) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kitsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.KitList{})
	return err
}

// Patch applies the patch and returns the patched kit.
func (c *FakeKits) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Kit, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kitsResource, c.ns, name, data, subresources...), &v1alpha1.Kit{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kit), err
}
