/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/kubectl/pkg/kustomize/apis/packaging/v1alpha1"
)

// FakePatchsets implements PatchsetInterface
type FakePatchsets struct {
	Fake *FakePackagingV1alpha1
	ns   string
}

var patchsetsResource = schema.GroupVersionResource{Group: "packaging.k8s.io", Version: "v1alpha1", Resource: "patchsets"}

var patchsetsKind = schema.GroupVersionKind{Group: "packaging.k8s.io", Version: "v1alpha1", Kind: "Patchset"}

// Get takes name of the patchset, and returns the corresponding patchset object, and an error if there is any.
func (c *FakePatchsets) Get(name string, options v1.GetOptions) (result *v1alpha1.Patchset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(patchsetsResource, c.ns, name), &v1alpha1.Patchset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Patchset), err
}

// List takes label and field selectors, and returns the list of Patchsets that match those selectors.
func (c *FakePatchsets) List(opts v1.ListOptions) (result *v1alpha1.PatchsetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(patchsetsResource, patchsetsKind, c.ns, opts), &v1alpha1.PatchsetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PatchsetList{}
	for _, item := range obj.(*v1alpha1.PatchsetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested patchsets.
func (c *FakePatchsets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(patchsetsResource, c.ns, opts))

}

// Create takes the representation of a patchset and creates it.  Returns the server's representation of the patchset, and an error, if there is any.
func (c *FakePatchsets) Create(patchset *v1alpha1.Patchset) (result *v1alpha1.Patchset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(patchsetsResource, c.ns, patchset), &v1alpha1.Patchset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Patchset), err
}

// Update takes the representation of a patchset and updates it. Returns the server's representation of the patchset, and an error, if there is any.
func (c *FakePatchsets) Update(patchset *v1alpha1.Patchset) (result *v1alpha1.Patchset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(patchsetsResource, c.ns, patchset), &v1alpha1.Patchset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Patchset), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePatchsets) UpdateStatus(patchset *v1alpha1.Patchset) (*v1alpha1.Patchset, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(patchsetsResource, "status", c.ns, patchset), &v1alpha1.Patchset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Patchset), err
}

// Delete takes name of the patchset and deletes it. Returns an error if one occurs.
func (c *FakePatchsets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(patchsetsResource, c.ns, name), &v1alpha1.Patchset{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePatchsets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(patchsetsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PatchsetList{})
	return err
}

// Patch applies the patch and returns the patched patchset.
func (c *FakePatchsets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Patchset, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(patchsetsResource, c.ns, name, data, subresources...), &v1alpha1.Patchset{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Patchset), err
}
